# Sets up to run the Android build script per the Travis CI documentation.
# Executes the script ./gradlew build connectedCheck, unless overridden by
# script test command, e.g., script: ./gradlew connectedAndroidTest
language: android

# sudo required for needed to install the e text-based web browser for displaying .html logs
sudo: required

# Configure the build to use Oracle JDK 8, which is required to compile for Android API 24 and newer
jdk:
  - oraclejdk8

# Install Android SDK components
android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.2

    # The SDK version used to compile your project
    - android-24

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
    #- addon-google_apis-google-24

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
  #   - sys-img-armeabi-v7a-android-24
    #- sys-img-x86-android-17

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

  # Unlock the screen
  # - adb shell input keyevent 82 &

  # Clear and capture logcat
  - adb logcat -c
  # Log all "worldwind" messages Info level messages
  #- adb logcat worldwind:I Explorer:W *:S
  - adb logcat *:W &
  #- adb -e logcat *:W | tee logcat.log > /dev/null 2>&1 &


# Overiding the default test command script to get more output
script: ./gradlew connectedCheck --info


#after_failure:

after_script:
  # - echo 'FAILURE'
  # Check apt configuration: http://docs.travis-ci.com/user/ci-environment/#apt-configuration
  # Comment out the lines below to show log about tests with app name customized on exports section.
  - sudo apt-get install -qq lynx
  - export MOD_NAME=emxsys/android-worldwind-explorer
  - export LOG_DIR=${TRAVIS_BUILD_DIR}/${MOD_NAME}/build/outputs/reports/androidTests/connected/
  - lynx --dump ${LOG_DIR}com.android.builder.testing.ConnectedDevice.html > myConnectedDevice.log
  - lynx --dump ${LOG_DIR}com.android.builder.testing.html > myTesting.log
  - for file in *.log; do echo "$file"; echo "====================="; cat "$file"; done || true
  # Append the emulator's logcat to the output
  # - echo 'LOGCAT'
  # - cat $HOME/logcat.log &

before_cache:
  # Use the caching configuration per the Travis CI documentation
  # See https://docs.travis-ci.com/user/languages/android#Caching
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/